### ISSUE TITLE
isLetterCorrect RATED 3

### ISSUE THREAD

**Issue by KarenDouglas** [KarenDouglas/word-guessing-game#3]
- when user guesses letter, compare letter to letters in word,
- if user guesses correctly, add to word
- if user guesses incorrectly, deduct score, add to wrong words box
-  if user guess correct word, render game over function
-  indicate whether user won/lost for render game over function
-  place variables in comments

**Comment by pm-912** [comment]
userScore is the variable for the user's current score
gameOver() is the function that will run when the game ends
